version: '2'
services:
  train-model:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/train.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
      - ./data:/opt/data
  test-model:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/test.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
      - ./data:/opt/data
  expose-model:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    ports:
      - 8000:8000