version: '2'
services:
  rbase-train:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/train.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
      - ./data:/opt/data
  rbase-test:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/test.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
      - ./data:/opt/data