version: '2'
services:
  train:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/train.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
      - ./data:/opt/data
  test:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/test.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
      - ./data:/opt/data
  expose:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/plumber.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
    ports:
      - 8000:8000