version: '2'
services:
  rbase:
    image: midockercontainerregistry.azurecr.io/r-model-pipeline-template
    command: Rscript /opt/scripts/model.R
    volumes:
      - ./scripts:/opt/scripts
      - ./models:/opt/models
      - ./data:/opt/data